project:
  title: Prospective cost-effectiveness of farmed fish stunning corporate commitments in Europe
  output-dir: ../5_rendered_output/

execute:
  warning: false
  
format:
  html: 
   toc: true
   embed-resources: true
   keep-md: false
   code-fold: show
   
editor: visual


